<a href="https://colab.research.google.com/github/AryaBenny/LEARN.PY/blob/main/Task9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create an 4x4 array containing the values ranging from 0-15 (use arange function). Then,

  a) split it equally along horizontal.

  b) split it as 4 parts vertically.

In [ ]:
#please provide your answer below this line.

import numpy as np
x = np.arange(0,16).reshape(4,4)
print("Array:\n",x)
print("\nEqually splitted array along horizontally:\n",np.hsplit(x,2))
print("\nArray split along vertically:\n",np.vsplit(x,4))

Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Equally splitted array along horizontally:
 [array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]

Array split along vertically:
 [array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


2. Create a 3x3 matrix using random module and then,

  a) Find the ceil of the matrix.

  b) Find the floor of the matrix.

In [ ]:
#please provide your answer below this line.

import numpy as np
X = np.random.rand(3,3)
print("Matrix:\n",X)
print("\nCeil of the matrix:\n",np.ceil(X))
print("\nFloor of the matrix:\n",np.floor(X))

Matrix:
 [[0.46668007 0.96184622 0.23705383]
 [0.13362504 0.9111554  0.09783347]
 [0.64438314 0.71243423 0.94143438]]

Ceil of the matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Floor of the matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


3. Create a random 1x4 array and print the random array and its shape.

  (use the shape function for finding the shape & use the same random we created here for both the below operations.)

  a) Squeeze the random array and print the squeezed array and its shape.
  
  b) Expand the random array by one axis and print the expanded array and its shape.

In [35]:
#please provide your answer below this line.

import numpy as np
a = np.random.rand(1,4)
print("Array:\n",a)
print("\nThe shape of the array is:\n",a.shape)
print("\nThe squeeze array:\n",np.squeeze(a))
print("\nThe shape of squeeze array:\n",np.squeeze(a).shape)
print("\nExpanded array:\n",np.expand_dims(a, axis=2))
print("\nThe shape of expanded array:\n",np.expand_dims(a, axis=2).shape)

Array:
 [[0.31574601 0.94190074 0.44463193 0.94101718]]

The shape of the array is:
 (1, 4)

The squeeze array:
 [0.31574601 0.94190074 0.44463193 0.94101718]

The shape of squeeze array:
 (4,)

Expanded array:
 [[[0.31574601]
  [0.94190074]
  [0.44463193]
  [0.94101718]]]

The shape of expanded array:
 (1, 4, 1)
