<a href="https://colab.research.google.com/github/AryaBenny/LEARN.PY/blob/main/Task13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1) Create a 3x3 array values ranging from 0-8. Find the sum of the elements in this array.

In [4]:
#please enter your code below this line.

import numpy as np
a = np.arange(0,9).reshape(3,3)
print("Array is:\n",a)
print("\nSum of the elements in the array is:\n",a.sum())

Array is:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Sum of the elements in the array is:
 36


2) Create a 3x3 array values ranging from 0-8. Find the row sum and column sum of this array.

In [11]:
#please enter your code below this line.

import numpy as np
x = np.arange(0,9).reshape(3,3)
print("Array is:\n",x)
print("\nRow sum of the array is:\n",x.sum(axis=1))
print("\nColumn sum of the array is:\n",x.sum(axis=0))

Array is:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Row sum of the array is:
 [ 3 12 21]

Column sum of the array is:
 [ 9 12 15]


3. Create a 4x4 array values ranging from 0-15. Now,

 a) Find the minimum value in the array.

 b) Find the maximum value in the array.

 c) Find the mean of the values in the array.

In [17]:
#please enter your code below this line.

import numpy as np
a = np.arange(0,16).reshape(4,4)
print("Array is:\n",a)
print("\nMinimum value in the array is:\n",a.min())
print("\nMaximum value in the array is:\n",a.max())
print("\nMean of the values in the array is:\n",a.mean())

Array is:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Minimum value in the array is:
 0

Maximum value in the array is:
 15

Mean of the values in the array is:
 7.5


4. Create an 10x10 array values ranging from 0-99. And,

 a) Print the 7th row.

 b) Print the rows from 4-8.

 c) Print the value at the index 5,5.

 d) Print the 5th column.

 e) Print the columns from 2-5.

In [5]:
#please enter your code below this line.

import numpy as np
x = np.arange(0,100).reshape(10,10)
print("Array is:\n",x)
print("\n7th row is:\n",x[7,:])
print("\nRows from 4-8 is:\n",x[4:8,:])
print("\nValue at the index 5,5 is:\n",x[5,5])
print("\n5th column is:\n",x[:,5])
print("\ncolumns from 2-5 is:\n",x[:,2:5])

Array is:
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]

7th row is:
 [70 71 72 73 74 75 76 77 78 79]

Rows from 4-8 is:
 [[40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]]

Value at the index 5,5 is:
 55

5th column is:
 [ 5 15 25 35 45 55 65 75 85 95]

columns from 2-5 is:
 [[ 2  3  4]
 [12 13 14]
 [22 23 24]
 [32 33 34]
 [42 43 44]
 [52 53 54]
 [62 63 64]
 [72 73 74]
 [82 83 84]
 [92 93 94]]
