<a href="https://colab.research.google.com/github/AryaBenny/LEARN.PY/blob/main/Task8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate a 3 x 3 matrix using random module.

In [ ]:
#please provide your answer below this line.

import numpy as np
Matrix = np.random.randint(10,size=(3,3))
print(Matrix)

[[3 6 5]
 [1 0 2]
 [9 2 7]]


2. Generate two 4 x 4 matrix using numpy and

  a) Reshape it to 2 x 8 matrix and vertically stack it.

  b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [12]:
#please provide your answer below this line.

import numpy as np
x = np.random.randint(20,size=(4,4))
y = np.random.randint(25,size=(4,4))
print(x)
print()
print(y)
print()
X = x.reshape(2,8)
Y = y.reshape(2,8)
print("Matrix after reshape: ")
print()
print(X)
print()
print(Y)
print()
matrix = np.vstack((X,Y))
print("Vertically stack Matrix: ")
print()
print(matrix)
print()
matrix = np.hstack((X,Y))
print("Horizontally stack Matrix: ")
print()
print(matrix)

[[ 2  7  5 11]
 [ 0  2  2  8]
 [ 3 19 15  0]
 [11 14  3 17]]

[[15  5  9 23]
 [19 13 11 16]
 [ 7 14  0 24]
 [ 9 19  3  3]]

Matrix after reshape: 

[[ 2  7  5 11  0  2  2  8]
 [ 3 19 15  0 11 14  3 17]]

[[15  5  9 23 19 13 11 16]
 [ 7 14  0 24  9 19  3  3]]

Vertically stack Matrix: 

[[ 2  7  5 11  0  2  2  8]
 [ 3 19 15  0 11 14  3 17]
 [15  5  9 23 19 13 11 16]
 [ 7 14  0 24  9 19  3  3]]

Horizontally stack Matrix: 

[[ 2  7  5 11  0  2  2  8 15  5  9 23 19 13 11 16]
 [ 3 19 15  0 11 14  3 17  7 14  0 24  9 19  3  3]]
