<a href="https://colab.research.google.com/github/AryaBenny/LEARN.PY/blob/main/Task12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1) Create an 4x4 array with elements ranging from 0-15, and find the trace of the array.

In [2]:
#please type your answer below this line.

import numpy as np
array = np.arange(0,16).reshape(4,4)
print("Array is:\n",array)
trace = np.trace(array)
print("\nTrace of the array is:\n",trace)

Array is:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Trace of the array is:
 30


2) Create a matrix with elements [6,1,1],[4,-2,5],[2,8,7]. Now find the inverse this matrix.

In [2]:
#please type your answer below this line.

import numpy as np
matrix = np.array([[6,1,1],[4,-2,5],[2,8,7]])
print("Matrix is:\n",matrix)
inverse = np.linalg.inv(matrix)
print("\nInverse of the matrix is:\n",inverse)

Matrix is:
 [[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]

Inverse of the matrix is:
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


3) Create an 3x3 array with elements ranging from 0-8, and find the norm this array.

In [6]:
#please type your answer below this line.

import numpy as np
array = np.arange(0,9).reshape(3,3)
print("Array is:\n",array)
norm = np.linalg.norm(array)
print("\nNorm of the array is:\n",norm)

Array is:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Norm of the array is:
 14.2828568570857


4) Create a 4x4 array whose value ranging from 0-15, and find the eigenvalues and eigenvectors of this array.

In [8]:
#please type your answer below this line.

import numpy as np
array = np.arange(0,16).reshape(4,4)
print("Array is:\n",array)
eigen = np.linalg.eig(array)
print("\nEigenvalues and eigenvectors of the array is:\n",eigen)

Array is:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Eigenvalues and eigenvectors of the array is:
 (array([ 3.24642492e+01, -2.46424920e+00,  2.55670932e-15, -1.93389056e-16]), array([[-0.11417645,  0.7327781 , -0.54471271,  0.09683789],
       [-0.3300046 ,  0.28974835,  0.76902356,  0.27269982],
       [-0.54583275, -0.15328139,  0.09609099, -0.8359133 ],
       [-0.76166089, -0.59631113, -0.32040185,  0.46637559]]))
