<a href="https://colab.research.google.com/github/AryaBenny/LEARN.PY/blob/main/Task10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1) Generate two 3x3 matrix and find it's dot product and take the transpose of the answer.

In [3]:
#please provide your answer below this line.

import numpy as np
x = np.arange(2,11).reshape(3,3)
y = np.arange(12,21).reshape(3,3)
print("Matrix X is:\n",x)
print("\nMatrix Y is:\n",y)
product = np.dot(x,y)
print("\nDot product of the matrices is:\n",product)
transpose = product.transpose()
print("\nTranspose of the product matrix is:\n",transpose)

Matrix X is:
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]

Matrix Y is:
 [[12 13 14]
 [15 16 17]
 [18 19 20]]

Dot product of the matrices is:
 [[141 150 159]
 [276 294 312]
 [411 438 465]]

Transpose of the product matrix is:
 [[141 276 411]
 [150 294 438]
 [159 312 465]]


2) Create a 3x3 matrix with elements [55,25,15], [30,44,2], [11,45,77]. Now find the determinant of the given matrix.

In [10]:
#please provide your answer below this line.

import numpy as np
matrix = np.array([[55,25,15],[30,44,2],[11,45,77]])
print("Matrix is:\n",matrix)
determinant = np.linalg.det(matrix)
print("\nDeterminant of the given matrix is:\n",determinant)

Matrix is:
 [[55 25 15]
 [30 44  2]
 [11 45 77]]

Determinant of the given matrix is:
 137180.0000000001
