<a href="https://colab.research.google.com/github/AryaBenny/LEARN.PY/blob/main/Task15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. For the given ndarray b below, evaluate whether elements in array b are equal to 'red'. Assign the result to b_bool and print the resultant boolean array.
b = np.array(["blue", "blue", "red", "blue"])

In [12]:
#please type your answer below this line.

import numpy as np
b = np.array(["blue","blue","red","blue"])
b_bool = b=='red'
print("Resultant boolean array is:\n", b_bool)

Resultant boolean array is:
 [False False  True False]


2. Create two arrays on containing elements from 0-5 and another containing elements from 6-10. Then append this array.

In [13]:
#please type your answer below this line.

import numpy as np
a = np.arange(0,6)
b = np.arange(6,11)
print("Appended array is:\n", np.append(a,b))

Appended array is:
 [ 0  1  2  3  4  5  6  7  8  9 10]


3. Create a 2x4 array containing values from 0-7 and another 2x4 containing values from 8-15. Now append this with,

  a) axis as 0

  b) axis as 1

In [14]:
#please type your answer below this line.

import numpy as np
x = np.arange(0,8).reshape(2,4)
y = np.arange(8,16).reshape(2,4)
print("Appended array with axis as 0 is:\n", np.append(x,y,axis=0))
print("\nAppended array with axis as 1 is:\n", np.append(x,y,axis=1))

Appended array with axis as 0 is:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Appended array with axis as 1 is:
 [[ 0  1  2  3  8  9 10 11]
 [ 4  5  6  7 12 13 14 15]]
